name: nft_showcase
description: A Flutter showcase project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.27.5
  dio: 4.0.6
  intl: 0.17.0
  card_swiper: ^2.0.4
  extended_image: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
